package daniel.interfaces.hibernate_examples.pojos;
// Generated 26.04.2016 11:40:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Artikel generated by hbm2java
 */
public class Artikel  implements java.io.Serializable {


     private Integer artikelId;
     private String bezeichnung;
     private BigDecimal preis;
     private Set<Bestellposition> bestellpositions = new HashSet<Bestellposition>(0);

    public Artikel() {
    }

	
    public Artikel(String bezeichnung, BigDecimal preis) {
        this.bezeichnung = bezeichnung;
        this.preis = preis;
    }
    public Artikel(String bezeichnung, BigDecimal preis, Set<Bestellposition> bestellpositions) {
       this.bezeichnung = bezeichnung;
       this.preis = preis;
       this.bestellpositions = bestellpositions;
    }
   
    public Integer getArtikelId() {
        return this.artikelId;
    }
    
    public void setArtikelId(Integer artikelId) {
        this.artikelId = artikelId;
    }
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }
    public BigDecimal getPreis() {
        return this.preis;
    }
    
    public void setPreis(BigDecimal preis) {
        this.preis = preis;
    }
    public Set<Bestellposition> getBestellpositions() {
        return this.bestellpositions;
    }
    
    public void setBestellpositions(Set<Bestellposition> bestellpositions) {
        this.bestellpositions = bestellpositions;
    }




}


