package daniel.interfaces.hibernate_examples.pojos;
// Generated 26.04.2016 11:40:40 by Hibernate Tools 4.3.1



/**
 * Bestellposition generated by hbm2java
 */
public class Bestellposition  implements java.io.Serializable {


     private Integer bestellpositionId;
     private Artikel artikel;
     private Bestellung bestellung;
     private int menge;

    public Bestellposition() {
    }

    public Bestellposition(Artikel artikel, Bestellung bestellung, int menge) {
       this.artikel = artikel;
       this.bestellung = bestellung;
       this.menge = menge;
    }
   
    public Integer getBestellpositionId() {
        return this.bestellpositionId;
    }
    
    public void setBestellpositionId(Integer bestellpositionId) {
        this.bestellpositionId = bestellpositionId;
    }
    public Artikel getArtikel() {
        return this.artikel;
    }
    
    public void setArtikel(Artikel artikel) {
        this.artikel = artikel;
    }
    public Bestellung getBestellung() {
        return this.bestellung;
    }
    
    public void setBestellung(Bestellung bestellung) {
        this.bestellung = bestellung;
    }
    public int getMenge() {
        return this.menge;
    }
    
    public void setMenge(int menge) {
        this.menge = menge;
    }




}


