package daniel.interfaces.hibernate_examples.pojos;
// Generated 26.04.2016 11:40:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bestellung generated by hbm2java
 */
public class Bestellung  implements java.io.Serializable {


     private Integer bestellungId;
     private Kunde kunde;
     private Date datum;
     private Set<Bestellposition> bestellpositions = new HashSet<Bestellposition>(0);

    public Bestellung() {
    }

	
    public Bestellung(Kunde kunde, Date datum) {
        this.kunde = kunde;
        this.datum = datum;
    }
    public Bestellung(Kunde kunde, Date datum, Set<Bestellposition> bestellpositions) {
       this.kunde = kunde;
       this.datum = datum;
       this.bestellpositions = bestellpositions;
    }
   
    public Integer getBestellungId() {
        return this.bestellungId;
    }
    
    public void setBestellungId(Integer bestellungId) {
        this.bestellungId = bestellungId;
    }
    public Kunde getKunde() {
        return this.kunde;
    }
    
    public void setKunde(Kunde kunde) {
        this.kunde = kunde;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Set<Bestellposition> getBestellpositions() {
        return this.bestellpositions;
    }
    
    public void setBestellpositions(Set<Bestellposition> bestellpositions) {
        this.bestellpositions = bestellpositions;
    }




}


