package daniel.interfaces.hibernate_examples.pojos;
// Generated 26.04.2016 11:40:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kunde generated by hbm2java
 */
public class Kunde  implements java.io.Serializable {


     private Integer kundeId;
     private String vorname;
     private Date geburtsdatum;
     private Set<Bestellung> bestellungs = new HashSet<Bestellung>(0);

    public Kunde() {
    }

	
    public Kunde(String vorname, Date geburtsdatum) {
        this.vorname = vorname;
        this.geburtsdatum = geburtsdatum;
    }
    public Kunde(String vorname, Date geburtsdatum, Set<Bestellung> bestellungs) {
       this.vorname = vorname;
       this.geburtsdatum = geburtsdatum;
       this.bestellungs = bestellungs;
    }
   
    public Integer getKundeId() {
        return this.kundeId;
    }
    
    public void setKundeId(Integer kundeId) {
        this.kundeId = kundeId;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public Date getGeburtsdatum() {
        return this.geburtsdatum;
    }
    
    public void setGeburtsdatum(Date geburtsdatum) {
        this.geburtsdatum = geburtsdatum;
    }
    public Set<Bestellung> getBestellungs() {
        return this.bestellungs;
    }
    
    public void setBestellungs(Set<Bestellung> bestellungs) {
        this.bestellungs = bestellungs;
    }




}


